name: CI/CD Workflow

on: workflow_dispatch

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::975049994612:role/oidc-cloudaws  # Replace with your role ARN
        aws-region: ap-south-1  # Replace with your AWS region

    # Step 4: Set up Docker for Amazon ECR login
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
    
    # Step 5: Build the Docker image
    - name: Build Docker image
      run: |
        cd ./frontend
        docker build -t test .
    
    # Step 6: Push the Docker image to Amazon ECR
    - name: Push Docker image to ECR
      run: |
        docker tag test:latest 975049994612.dkr.ecr.ap-south-1.amazonaws.com/test:latest
        docker push 975049994612.dkr.ecr.ap-south-1.amazonaws.com/test:latest
