name: Deploy Lambda Function

on: workflow_dispatch

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: runs-on: self-hosted

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2
